version: '3'
services:
  chatbot_jupyter_flask:
    build: .
    container_name: chatbot_jupyter_flask
    restart: always
    ports:
      - "8888:8888"
      - "80:5000"
    links:
      - redis_lins_jupyter
    volumes:
      - ./material:/home/jovyan/work
    environment:
      - "GRANT_SUDO: yes"

  chatbot_ngrok:
    image: wernight/ngrok
    container_name: chatbot_ngrok
    depends_on:
      - chatbot_jupyter_flask
    restart: always
    ports:
      - "4040:4040"
    links:
      - chatbot_jupyter_flask:http
    command: ngrok http --authtoken=upGfpT3EYQymmC9WbXHc_DWHNFxTmJTm4Ph1UEuDN chatbot_jupyter_flask:5000

  redis_lins_jupyter:
    image: redislabs/rejson
    container_name: -redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
